name: Build Project
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the app
        run: xcodebuild -project PizzaRatings-iOS.xcodeproj -scheme PizzaRatings-iOS -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
