name: Build Project
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the app
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: PizzaRatings-iOS.xcodeproj
          scheme: PizzaRatings-iOS
          allow-provisioning-updates: true
          action: build
