name: Build Project
on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the app
        run: xcodebuild build -workspace PizzaRatings-iOS.xcworkspace -scheme PizzaRatings-iOS
